#!/usr/bin/env python

from util import float_u, get_deriv
import sys
import numpy as np
from pylab import *
from scipy.special import erf

x,y,totals, index = np.loadtxt( sys.argv[1] , unpack = True, delimiter= "\t", converters = { 0: float_u } )

pre = None
if y[0] == 0:
    if not (1 in y.tolist() ) or y.tolist().index(1) == 0:
        print "None"
        exit( 1)
    pre = y.tolist().index(1)
elif y[0] == 1:
    if not (0 in y.tolist() ) or y.tolist().index(0) == 0:
        print "None"
        exit( 1)
    pre = y.tolist().index(0)
else:
    raise Exception

thresh = ( x[pre -1] + x[pre] ) / 2.0
print thresh
