#!/usr/bin/env python

from io import StringIO
import sys
import numpy as np
from pylab import *

for f in sys.argv[1:]:
    print f
    d = np.loadtxt( f , unpack = True, delimiter="\t" )
    y = d[1]
    print y
    plot( d , "o" )

show()
